Repository boostcampwm-2022/android07-Puzzle, pull requests merged in 2022-11, with the labels that each got.

#16 feature : 스플래시 화면
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/juniori/puzzle/MainActivity.kt
  app/src/main/res/drawable/splash_background.9.png
  app/src/main/res/values/themes.xml
Labels: feature

#25 feat : Login 액티비티 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/juniori/puzzle/MainActivity.kt
  app/src/main/java/com/juniori/puzzle/PuzzleApp.kt
  app/src/main/java/com/juniori/puzzle/data/Resource.kt
  app/src/main/java/com/juniori/puzzle/data/auth/AuthModule.kt
  app/src/main/java/com/juniori/puzzle/data/auth/AuthRepository.kt
  app/src/main/java/com/juniori/puzzle/data/auth/AuthRepositoryImpl.kt
  app/src/main/java/com/juniori/puzzle/ui/login/LoginActivity.kt
  app/src/main/java/com/juniori/puzzle/ui/login/LoginViewModel.kt
  app/src/main/java/com/juniori/puzzle/util/Extensions.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: feature

#27 Feature : camera activity
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/juniori/puzzle/CameraActivity.kt
  app/src/main/res/layout/activity_camera.xml
  app/src/main/res/values/strings.xml
Labels: feature

#26 design: 홈 UI & 환영문구
  app/build.gradle
  app/src/main/java/com/juniori/puzzle/MainActivity.kt
  app/src/main/java/com/juniori/puzzle/adapter/PuzzleBindingAdapter.kt
  app/src/main/java/com/juniori/puzzle/ui/home/HomeFragment.kt
  app/src/main/java/com/juniori/puzzle/ui/home/HomeViewModel.kt
  app/src/main/res/drawable/home_background_image.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: feature, design

#33 feat: 현재 좌표 가져오기 & openWeather retrofit 연결
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/juniori/puzzle/data/weather/WeatherItem.kt
  app/src/main/java/com/juniori/puzzle/data/weather/WeatherRepository.kt
  app/src/main/java/com/juniori/puzzle/data/weather/WeatherRepositoryImpl.kt
  app/src/main/java/com/juniori/puzzle/data/weather/WeatherResponse.kt
  app/src/main/java/com/juniori/puzzle/di/WeatherModule.kt
  app/src/main/java/com/juniori/puzzle/network/WeatherService.kt
  app/src/main/java/com/juniori/puzzle/ui/home/HomeFragment.kt
  app/src/main/java/com/juniori/puzzle/ui/home/HomeViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/mypage/MyPageFragment.kt
  app/src/main/res/drawable/home_refresh_icon.xml
  app/src/main/res/layout/fragment_home.xml
Labels: feature

#35 feat: add video
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/juniori/puzzle/MainActivity.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/AddVideoBottomSheet.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/AddVideoViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/camera/CameraActivity.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/upload/UploadStep1Fragment.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/upload/UploadStep2Fragment.kt
  app/src/main/res/layout/activity_camera.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/bottomsheet_addvideo.xml
  app/src/main/res/layout/fragment_upload_step1.xml
  app/src/main/res/layout/fragment_upload_step2.xml
  app/src/main/res/menu/main_bottomnavigation.xml
  app/src/main/res/navigation/main_bottomnavigation.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature

#31 Refactoring: 클린 아키텍쳐 적용
  app/src/main/java/com/juniori/puzzle/data/auth/AuthRepository.kt
  app/src/main/java/com/juniori/puzzle/data/auth/AuthRepositoryImpl.kt
  app/src/main/java/com/juniori/puzzle/data/firebase/FireStoreDataSource.kt
  app/src/main/java/com/juniori/puzzle/data/firebase/NetworkModule.kt
  app/src/main/java/com/juniori/puzzle/data/video/VideoRemoteDataSource.kt
  app/src/main/java/com/juniori/puzzle/data/video/VideoRemoteDataSourceImpl.kt
  app/src/main/java/com/juniori/puzzle/data/video/VideoRepositoryImpl.kt
  app/src/main/java/com/juniori/puzzle/data/video/VideoRepositoryMockImpl.kt
  app/src/main/java/com/juniori/puzzle/di/AuthModule.kt
  app/src/main/java/com/juniori/puzzle/di/HiltAnnotation.kt
  app/src/main/java/com/juniori/puzzle/di/VideoModule.kt
  app/src/main/java/com/juniori/puzzle/domain/entity/LocationInfoEntity.kt
  app/src/main/java/com/juniori/puzzle/domain/entity/UserInfoEntity.kt
  app/src/main/java/com/juniori/puzzle/domain/entity/VideoInfoEntity.kt
  app/src/main/java/com/juniori/puzzle/domain/repository/AuthRepository.kt
  app/src/main/java/com/juniori/puzzle/domain/repository/VideoRepository.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/DeleteVideoUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/GetLocationInfoUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/GetMyVideoListUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/GetSearchedMyVideoUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/GetSearchedSocialVideoListUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/GetSocialVideoListUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/GetUserInfoUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/GetVideoFileUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/ModifyNicknameUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/PostVideoUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/RequestLoginUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/RequestLogoutUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/SetVideoScopeUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/UpdateLikeStatusUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/WithdrawAccountUseCase.kt
  app/src/main/java/com/juniori/puzzle/mock/MockVideoData.kt
  app/src/main/java/com/juniori/puzzle/ui/home/HomeViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/login/LoginViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/mygallery/MyGalleryViewModel.kt
  app/src/main/java/com/juniori/puzzle/util/SortType.kt
Labels: refactor

#53 feature: 날씨 UI
  app/build.gradle
  app/src/main/java/com/juniori/puzzle/adapter/PuzzleBindingAdapter.kt
  app/src/main/java/com/juniori/puzzle/adapter/WeatherRecyclerViewAdapter.kt
  app/src/main/java/com/juniori/puzzle/data/weather/WeatherItem.kt
  app/src/main/java/com/juniori/puzzle/data/weather/WeatherRepository.kt
  app/src/main/java/com/juniori/puzzle/data/weather/WeatherRepositoryImpl.kt
  app/src/main/java/com/juniori/puzzle/data/weather/WeatherResponse.kt
  app/src/main/java/com/juniori/puzzle/di/WeatherModule.kt
  app/src/main/java/com/juniori/puzzle/network/WeatherService.kt
  app/src/main/java/com/juniori/puzzle/ui/home/HomeFragment.kt
  app/src/main/java/com/juniori/puzzle/ui/home/HomeViewModel.kt
  app/src/main/java/com/juniori/puzzle/util/Extensions.kt
  app/src/main/java/com/juniori/puzzle/util/WeatherConverter.kt
  app/src/main/java/com/juniori/puzzle/util/WeatherDateFormatter.kt
  app/src/main/res/drawable-hdpi/home_background_image.png
  app/src/main/res/drawable-mdpi/home_background_image.png
  app/src/main/res/drawable-xhdpi/home_background_image.png
  app/src/main/res/drawable-xxhdpi/home_background_image.png
  app/src/main/res/drawable-xxxhdpi/home_background_image.png
  app/src/main/res/drawable/all_toolbar_background.xml
  app/src/main/res/drawable/home_background_image.png
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_weather_detail.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/fonts.xml
  app/src/main/res/values/shapes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature, design

#58 feat: fire store, storage 요청 함수 구현 및 함수 명세
  app/src/main/java/com/juniori/puzzle/MainActivity.kt
  app/src/main/java/com/juniori/puzzle/data/auth/AuthRepositoryImpl.kt
  app/src/main/java/com/juniori/puzzle/data/firebase/FireStoreDataSource.kt
  app/src/main/java/com/juniori/puzzle/data/firebase/FirestoreDataSource.kt
  app/src/main/java/com/juniori/puzzle/data/firebase/FirestoreService.kt
  app/src/main/java/com/juniori/puzzle/data/firebase/NetworkModule.kt
  app/src/main/java/com/juniori/puzzle/data/firebase/StorageDataSource.kt
  app/src/main/java/com/juniori/puzzle/data/firebase/StorageService.kt
  app/src/main/java/com/juniori/puzzle/data/firebase/dto/StructuredQuery.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/AddVideoBottomSheet.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/AddVideoViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/upload/UploadStep1Fragment.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/upload/UploadStep2Fragment.kt
  app/src/main/java/com/juniori/puzzle/ui/home/HomeViewModel.kt
  app/src/main/java/com/juniori/puzzle/util/Query.kt
  app/src/main/java/com/juniori/puzzle/util/SortType.kt
Labels: feature, database

#68 feat : play video activity 구현 및 bottomsheet 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/juniori/puzzle/data/firebase/FirestoreDataSource.kt
  app/src/main/java/com/juniori/puzzle/data/firebase/FirestoreService.kt
  app/src/main/java/com/juniori/puzzle/data/firebase/StorageDataSource.kt
  app/src/main/java/com/juniori/puzzle/data/firebase/StorageService.kt
  app/src/main/java/com/juniori/puzzle/data/firebase/dto/FirestoreDTO.kt
  app/src/main/java/com/juniori/puzzle/data/firebase/dto/VideoItem.kt
  app/src/main/java/com/juniori/puzzle/domain/entity/UserInfoEntity.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/AddVideoViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/upload/UploadStep2Fragment.kt
  app/src/main/java/com/juniori/puzzle/ui/home/HomeViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/playvideo/PlayVideoActivity.kt
  app/src/main/java/com/juniori/puzzle/ui/playvideo/PlayVideoBottomSheet.kt
  app/src/main/java/com/juniori/puzzle/ui/playvideo/PlayVideoViewModel.kt
  app/src/main/res/drawable/play_go_back.xml
  app/src/main/res/drawable/play_setting.xml
  app/src/main/res/layout/activity_playvideo.xml
  app/src/main/res/layout/bottomsheet_playvideo.xml
  app/src/main/res/menu/playvideo_menu.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature, database

#57 feat : 마이페이지 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/juniori/puzzle/SingleLiveEvent.kt
  app/src/main/java/com/juniori/puzzle/data/auth/AuthRepositoryImpl.kt
  app/src/main/java/com/juniori/puzzle/domain/repository/AuthRepository.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/ModifyNicknameUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/RequestWithdrawUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/UpdateNicknameUseCase.kt
  app/src/main/java/com/juniori/puzzle/ui/home/HomeViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/juniori/puzzle/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/mypage/UpdateNicknameActivity.kt
  app/src/main/res/drawable/cursor_background.xml
  app/src/main/res/drawable/text_container_background.xml
  app/src/main/res/layout/activity_update_nickname.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/values/strings.xml
Labels: feature

#75 feat: PR 충돌 해결 & 업로드 공개 to 비공개 다이얼로그 & 정보 입력란 추가
  app/src/main/java/com/juniori/puzzle/di/VideoModule.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/AddVideoViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/upload/UploadStep2Fragment.kt
  app/src/main/java/com/juniori/puzzle/util/GalleryDiffCallBack.kt
  app/src/main/res/drawable/upload2_golfcourse_24dp.xml
  app/src/main/res/drawable/upload2_time_icon_24dp.xml
  app/src/main/res/layout/fragment_upload_step1.xml
  app/src/main/res/layout/fragment_upload_step2.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature

#74 feat: 로딩, 네트워크 끊김 화면 구현
  app/build.gradle
  app/src/main/java/com/juniori/puzzle/data/weather/WeatherRepository.kt
  app/src/main/java/com/juniori/puzzle/data/weather/WeatherRepositoryImpl.kt
  app/src/main/java/com/juniori/puzzle/di/DialogModule.kt
  app/src/main/java/com/juniori/puzzle/di/HiltAnnotation.kt
  app/src/main/java/com/juniori/puzzle/di/NetworkModule.kt
  app/src/main/java/com/juniori/puzzle/di/WeatherModule.kt
  app/src/main/java/com/juniori/puzzle/ui/home/HomeFragment.kt
  app/src/main/java/com/juniori/puzzle/ui/home/HomeViewModel.kt
  app/src/main/java/com/juniori/puzzle/util/Extensions.kt
  app/src/main/java/com/juniori/puzzle/util/StateManager.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/loading_layout.xml
  app/src/main/res/layout/network_fail_layout.xml
  app/src/main/res/raw/loading_golf.json
  app/src/main/res/raw/loading_progress.json
  app/src/main/res/raw/network_fail.json
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: feature, design

#76 fix: 영상 제한시간 초과시 다시 추가할 수 없던 오류 수정
  app/src/main/java/com/juniori/puzzle/ui/addvideo/AddVideoActionState.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/AddVideoBottomSheet.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/AddVideoViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/upload/UploadStep2Fragment.kt
  app/src/main/java/com/juniori/puzzle/ui/home/HomeFragment.kt
  app/src/main/java/com/juniori/puzzle/util/StateManager.kt
  app/src/main/res/layout/bottomsheet_addvideo.xml
  app/src/main/res/layout/fragment_upload_step2.xml
  app/src/main/res/values/shapes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: bug, feature

#83 feat : 영상 정보 시트 구현 및 UserInfo database 생성
  app/src/main/java/com/juniori/puzzle/adapter/PuzzleBindingAdapter.kt
  app/src/main/java/com/juniori/puzzle/data/firebase/FirestoreDataSource.kt
  app/src/main/java/com/juniori/puzzle/data/firebase/FirestoreService.kt
  app/src/main/java/com/juniori/puzzle/data/firebase/dto/UserItem.kt
  app/src/main/java/com/juniori/puzzle/ui/login/LoginViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/mygallery/MyGalleryFragment.kt
  app/src/main/java/com/juniori/puzzle/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/juniori/puzzle/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/othersgallery/OthersGalleryFragment.kt
  app/src/main/java/com/juniori/puzzle/ui/playvideo/PlayVideoActivity.kt
  app/src/main/java/com/juniori/puzzle/ui/playvideo/PlayVideoBottomSheet.kt
  app/src/main/java/com/juniori/puzzle/ui/playvideo/PlayVideoViewModel.kt
  app/src/main/java/com/juniori/puzzle/util/Query.kt
  app/src/main/res/drawable/all_outlined_box.xml
  app/src/main/res/layout/bottomsheet_playvideo.xml
  app/src/main/res/layout/item_information.xml
Labels: feature, database

#92 fix : dto likeduidList 내부 값 수정
  app/src/main/java/com/juniori/puzzle/data/firebase/FirestoreDataSource.kt
  app/src/main/java/com/juniori/puzzle/data/firebase/dto/FirestoreValues.kt
  app/src/main/java/com/juniori/puzzle/data/firebase/dto/VideoItem.kt
Labels: bug

#93 fix: 충돌 해결하다가 import 빠뜨린 것 추가
  app/src/main/java/com/juniori/puzzle/adapter/PuzzleBindingAdapter.kt
Labels: bug

#84 feat : 마이페이지 고도화 작업
  app/src/main/java/com/juniori/puzzle/adapter/PuzzleBindingAdapter.kt
  app/src/main/java/com/juniori/puzzle/data/auth/AuthRepositoryImpl.kt
  app/src/main/java/com/juniori/puzzle/domain/repository/AuthRepository.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/RequestLogoutUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/RequestWithdrawUseCase.kt
  app/src/main/java/com/juniori/puzzle/ui/login/LoginViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/juniori/puzzle/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/mypage/UpdateNicknameActivity.kt
  app/src/main/res/layout/activity_update_nickname.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#94 feat : 좋아요 기능 구현
  app/src/main/java/com/juniori/puzzle/adapter/PuzzleBindingAdapter.kt
  app/src/main/java/com/juniori/puzzle/data/firebase/FirestoreDataSource.kt
  app/src/main/java/com/juniori/puzzle/ui/playvideo/PlayVideoActivity.kt
  app/src/main/java/com/juniori/puzzle/ui/playvideo/PlayVideoViewModel.kt
  app/src/main/res/drawable/play_comment_icon.xml
  app/src/main/res/drawable/play_like_not_selected.xml
  app/src/main/res/drawable/play_like_selected.xml
  app/src/main/res/layout/activity_playvideo.xml
  app/src/main/res/values/themes.xml
Labels: feature

#95 feat : 페이징 방식 변경, 스낵바
  app/build.gradle
  app/src/main/java/com/juniori/puzzle/ui/mygallery/MyGalleryFragment.kt
  app/src/main/java/com/juniori/puzzle/ui/mygallery/MyGalleryViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/othersgallery/OtherGalleryAdapter.kt
  app/src/main/java/com/juniori/puzzle/ui/othersgallery/OthersGalleryFragment.kt
  app/src/main/java/com/juniori/puzzle/ui/othersgallery/OthersGalleryViewModel.kt
  app/src/main/java/com/juniori/puzzle/util/GalleryState.kt
  app/src/main/res/drawable/flag.png
  app/src/main/res/drawable/golf_ball.png
  app/src/main/res/drawable/grass_rectangle.png
  app/src/main/res/drawable/home_background_image.png
  app/src/main/res/drawable/home_icon.png
  app/src/main/res/drawable/splash_background.9.png
  app/src/main/res/layout/fragment_mygallery.xml
  app/src/main/res/layout/fragment_othersgallery.xml
  app/src/main/res/values/strings.xml
Labels: feature, refactor
