Repository boostcampwm-2022/android07-Puzzle, pull requests merged in 2022-12, with the labels that each got.

#97 feat: 그린 기울기 구하기, 홈화면 리팩토링
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/juniori/puzzle/adapter/WeatherRecyclerViewAdapter.kt
  app/src/main/java/com/juniori/puzzle/data/location/LocationDataSource.kt
  app/src/main/java/com/juniori/puzzle/data/location/LocationDataSourceImpl.kt
  app/src/main/java/com/juniori/puzzle/data/location/LocationRepositoryImpl.kt
  app/src/main/java/com/juniori/puzzle/data/weather/WeatherDataSource.kt
  app/src/main/java/com/juniori/puzzle/data/weather/WeatherDataSourceImpl.kt
  app/src/main/java/com/juniori/puzzle/data/weather/WeatherRepository.kt
  app/src/main/java/com/juniori/puzzle/di/LocationModule.kt
  app/src/main/java/com/juniori/puzzle/di/WeatherModule.kt
  app/src/main/java/com/juniori/puzzle/domain/entity/LocationInfoEntity.kt
  app/src/main/java/com/juniori/puzzle/domain/entity/WeatherEntity.kt
  app/src/main/java/com/juniori/puzzle/domain/repository/LocationRepository.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/GetAddressUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/GetSearchedSocialVideoListUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/GetWeatherUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/RegisterLocationListenerUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/UnregisterLocationListenerUseCase.kt
  app/src/main/java/com/juniori/puzzle/network/WeatherService.kt
  app/src/main/java/com/juniori/puzzle/ui/home/HomeFragment.kt
  app/src/main/java/com/juniori/puzzle/ui/home/HomeViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/sensor/GolfBallView.kt
  app/src/main/java/com/juniori/puzzle/ui/sensor/SensorActivity.kt
  app/src/main/java/com/juniori/puzzle/util/WeatherConverter.kt
  app/src/main/res/drawable-hdpi/splash_img.png
  app/src/main/res/drawable-mdpi/splash_img.png
  app/src/main/res/drawable-xhdpi/splash_img.png
  app/src/main/res/drawable-xxhdpi/splash_img.png
  app/src/main/res/drawable-xxxhdpi/splash_img.png
  app/src/main/res/layout/activity_sensor.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_weather_detail.xml
  app/src/main/res/values/themes.xml
Labels: feature, refactor

#105 feat: 동영상 공유 및 삭제 다이얼로그 표시 구현
  app/src/main/java/com/juniori/puzzle/ui/playvideo/PlayVideoActivity.kt
  app/src/main/res/values/strings.xml
Labels: feature

#101 fix: 업로드2 화면 썸네일 안보이고, 메모 서버에 업로드 안되는 오류 수정
  app/src/main/java/com/juniori/puzzle/di/VideoModule.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/AddVideoActionState.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/AddVideoBottomSheet.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/AddVideoUiState.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/AddVideoViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/camera/CameraActivity.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/upload/UploadStep1Fragment.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/upload/UploadStep2Fragment.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/upload/UploadViewModel.kt
  app/src/main/java/com/juniori/puzzle/util/VideoMetaDataUtil.kt
  app/src/main/res/layout/fragment_upload_step1.xml
  app/src/main/res/layout/fragment_upload_step2.xml
Labels: bug, refactor

#107 feat: 동영상 피드 다이나믹 컬러 적용, 디자인 일부 수정
  app/build.gradle
  app/src/main/java/com/juniori/puzzle/adapter/HomeBindingAdapter.kt
  app/src/main/java/com/juniori/puzzle/adapter/ImageBindingAdapter.kt
  app/src/main/java/com/juniori/puzzle/adapter/PuzzleBindingAdapter.kt
  app/src/main/res/drawable/all_toolbar_background.xml
  app/src/main/res/drawable/alpha_gradient_background.xml
  app/src/main/res/drawable/play_comment_icon.xml
  app/src/main/res/drawable/play_like_not_selected.xml
  app/src/main/res/drawable/play_like_selected.xml
  app/src/main/res/layout/activity_playvideo.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_mygallery.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_othersgallery.xml
  app/src/main/res/layout/fragment_upload_step1.xml
  app/src/main/res/layout/item_gallery_recycler.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature, design

#112 fix : 비디오 재생화면 생명주기 관련 수정
  app/src/main/java/com/juniori/puzzle/data/firebase/FirestoreDataSource.kt
  app/src/main/java/com/juniori/puzzle/ui/playvideo/PlayVideoActivity.kt
Labels: bug

#110 fix: 영상 촬영 권한 문제 해결, MetaDataRetriever 호출문에서 앱 터지지 않도록 수정
  app/src/main/java/com/juniori/puzzle/ui/addvideo/camera/CameraActivity.kt
  app/src/main/java/com/juniori/puzzle/util/FileIOExtenstions.kt
  app/src/main/java/com/juniori/puzzle/util/VideoMetaDataUtil.kt
  app/src/main/res/values/strings.xml
Labels: bug

#121 fix : 페이징시 몇가지 문제 수정
  app/src/main/java/com/juniori/puzzle/domain/entity/VideoInfoEntity.kt
  app/src/main/java/com/juniori/puzzle/ui/mygallery/MyGalleryFragment.kt
  app/src/main/java/com/juniori/puzzle/ui/othersgallery/OthersGalleryViewModel.kt
Labels: bug

#123 feature : 영어 지원
  app/src/main/java/com/juniori/puzzle/ui/addvideo/upload/UploadStep2Fragment.kt
  app/src/main/res/layout/activity_camera.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/array.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: design

#120 feat : 비디오 압축 기능 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/juniori/puzzle/di/NetworkModule.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/upload/UploadStep2Fragment.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/upload/UploadViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/playvideo/PlayVideoViewModel.kt
  app/src/main/java/com/juniori/puzzle/util/ProgressDialog.kt
  app/src/main/res/layout/dialog_progress.xml
  app/src/main/res/values/strings.xml
Labels: feature

#126 design: 다크모드 대응, 다이얼로그 통일
  app/src/main/java/com/juniori/puzzle/adapter/ImageBindingAdapter.kt
  app/src/main/java/com/juniori/puzzle/ui/home/HomeViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/juniori/puzzle/ui/othersgallery/OthersGalleryFragment.kt
  app/src/main/java/com/juniori/puzzle/ui/playvideo/PlayVideoActivity.kt
  app/src/main/java/com/juniori/puzzle/ui/playvideo/PlayVideoBottomSheet.kt
  app/src/main/java/com/juniori/puzzle/ui/sensor/GolfBallView.kt
  app/src/main/java/com/juniori/puzzle/util/PuzzleDialog.kt
  app/src/main/res/drawable-hdpi/splash_img.png
  app/src/main/res/drawable-mdpi/splash_img.png
  app/src/main/res/drawable-xhdpi/splash_img.png
  app/src/main/res/drawable-xxhdpi/splash_img.png
  app/src/main/res/drawable-xxxhdpi/splash_img.png
  app/src/main/res/drawable/all_location_icon.xml
  app/src/main/res/drawable/all_memo_background.xml
  app/src/main/res/drawable/all_popup_background.xml
  app/src/main/res/drawable/all_search_view_background.xml
  app/src/main/res/drawable/flag.png
  app/src/main/res/drawable/golf_ball.png
  app/src/main/res/drawable/grass_rectangle.png
  app/src/main/res/drawable/home_background_image.png
  app/src/main/res/drawable/home_icon.png
  app/src/main/res/drawable/home_refresh_icon.xml
  app/src/main/res/drawable/main_addvideoicon_24dp.xml
  app/src/main/res/drawable/main_homeicon_24dp.xml
  app/src/main/res/drawable/main_mygalleryicon_24dp.xml
  app/src/main/res/drawable/main_othersgalleryicon_24dp.xml
  app/src/main/res/drawable/play_calendar_icon.xml
  app/src/main/res/drawable/play_go_back.xml
  app/src/main/res/drawable/play_like_selected.xml
  app/src/main/res/drawable/play_setting.xml
  app/src/main/res/drawable/text_container_background.xml
  app/src/main/res/drawable/upload2_golfcourse_24dp.xml
  app/src/main/res/drawable/upload2_time_icon_24dp.xml
  app/src/main/res/layout/activity_camera.xml
  app/src/main/res/layout/activity_playvideo.xml
  app/src/main/res/layout/activity_sensor.xml
  app/src/main/res/layout/activity_update_nickname.xml
  app/src/main/res/layout/bottomsheet_addvideo.xml
  app/src/main/res/layout/bottomsheet_playvideo.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_othersgallery.xml
  app/src/main/res/layout/item_information.xml
  app/src/main/res/layout/item_popup_list.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/array.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/shapes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: feature, design, refactor

#128 feature : 페이징 스낵바 & 제거, private시 데이터 처리
  app/src/main/java/com/juniori/puzzle/data/video/VideoRepositoryImpl.kt
  app/src/main/java/com/juniori/puzzle/ui/mygallery/MyGalleryFragment.kt
  app/src/main/java/com/juniori/puzzle/ui/mygallery/MyGalleryViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/othersgallery/OthersGalleryFragment.kt
  app/src/main/java/com/juniori/puzzle/ui/othersgallery/OthersGalleryViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/playvideo/PlayVideoActivity.kt
  app/src/main/java/com/juniori/puzzle/util/PagingConst.kt
  app/src/main/java/com/juniori/puzzle/util/PlayResultConst.kt
  app/src/main/res/values-en/strings.xml
Labels: bug, design

#129 design: 테블릿 사이즈용 dimen 추가
  app/src/main/java/com/juniori/puzzle/data/location/LocationDataSourceImpl.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/camera/CameraActivity.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/upload/UploadStep2Fragment.kt
  app/src/main/java/com/juniori/puzzle/ui/mygallery/MyGalleryFragment.kt
  app/src/main/java/com/juniori/puzzle/ui/othersgallery/OthersGalleryFragment.kt
  app/src/main/res/drawable/camera_button.xml
  app/src/main/res/drawable/camera_button_recording.xml
  app/src/main/res/layout/activity_camera.xml
  app/src/main/res/layout/bottomsheet_playvideo.xml
  app/src/main/res/layout/dialog_progress.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_othersgallery.xml
  app/src/main/res/layout/fragment_upload_step2.xml
  app/src/main/res/layout/item_gallery_recycler.xml
  app/src/main/res/layout/item_popup_list.xml
  app/src/main/res/layout/item_weather_detail.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-sw600dp/dimens.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature, design

#131 bugfix : 회원탈퇴 기능 수정
  app/src/main/java/com/juniori/puzzle/data/auth/AuthRepositoryImpl.kt
  app/src/main/java/com/juniori/puzzle/domain/repository/AuthRepository.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/RequestWithdrawUseCase.kt
  app/src/main/java/com/juniori/puzzle/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/juniori/puzzle/ui/mypage/MyPageViewModel.kt
Labels: bug

#133 bug: 네트워크 및 위치 권한에 따른 날씨 화면 대응
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/juniori/puzzle/adapter/PuzzleBindingAdapter.kt
  app/src/main/java/com/juniori/puzzle/data/location/LocationDataSource.kt
  app/src/main/java/com/juniori/puzzle/data/location/LocationDataSourceImpl.kt
  app/src/main/java/com/juniori/puzzle/data/location/LocationInfo.kt
  app/src/main/java/com/juniori/puzzle/data/location/LocationRepositoryImpl.kt
  app/src/main/java/com/juniori/puzzle/data/weather/WeatherDataSourceImpl.kt
  app/src/main/java/com/juniori/puzzle/domain/repository/LocationRepository.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/GetLocationInfoUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/GetWeatherUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/RegisterLocationListenerUseCase.kt
  app/src/main/java/com/juniori/puzzle/network/WeatherService.kt
  app/src/main/java/com/juniori/puzzle/ui/home/HomeFragment.kt
  app/src/main/java/com/juniori/puzzle/ui/home/HomeViewModel.kt
  app/src/main/java/com/juniori/puzzle/util/StateManager.kt
  app/src/main/res/layout/activity_playvideo.xml
  app/src/main/res/layout/bottomsheet_addvideo.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_mygallery.xml
  app/src/main/res/layout/fragment_othersgallery.xml
  app/src/main/res/layout/network_fail_layout.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: bug

#132 feature: 동영상 스와이프 기능 추가, 갤러리,재생 파트 구조 변경
  app/src/main/java/com/juniori/puzzle/data/firebase/FirestoreDataSource.kt
  app/src/main/java/com/juniori/puzzle/data/firebase/dto/StructuredQuery.kt
  app/src/main/java/com/juniori/puzzle/data/video/VideoRepositoryImpl.kt
  app/src/main/java/com/juniori/puzzle/data/video/VideoRepositoryImpl2.kt
  app/src/main/java/com/juniori/puzzle/data/video/VideoRepositoryMockImpl.kt
  app/src/main/java/com/juniori/puzzle/di/VideoModule.kt
  app/src/main/java/com/juniori/puzzle/domain/repository/VideoRepository.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/FetchMyFirstVideosUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/FetchMyNextVideosUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/FetchOthersFirstVideosUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/FetchOthersNextVideosUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/GetMyVideoFetchingStateUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/GetMyVideoListUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/GetMyVideosUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/GetOthersVideoFetchingStateUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/GetOthersVideosUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/GetSearchedMyVideoUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/GetSearchedSocialVideoListUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/GetSocialVideoListUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/GetUserInfoByUidUseCase.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/upload/UploadViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/mygallery/MyGalleryAdapter.kt
  app/src/main/java/com/juniori/puzzle/ui/mygallery/MyGalleryFragment.kt
  app/src/main/java/com/juniori/puzzle/ui/mygallery/MyGalleryViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/othersgallery/OthersGalleryAdapter.kt
  app/src/main/java/com/juniori/puzzle/ui/othersgallery/OthersGalleryFragment.kt
  app/src/main/java/com/juniori/puzzle/ui/othersgallery/OthersGalleryViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/playvideo/PlayVideoActivity.kt
  app/src/main/java/com/juniori/puzzle/ui/playvideo/PlayVideoDetailFragment.kt
  app/src/main/java/com/juniori/puzzle/ui/playvideo/PlayVideoDetailViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/playvideo/PlayVideoViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/playvideo/VideoSwipePagerAdapter.kt
  app/src/main/java/com/juniori/puzzle/util/Extensions.kt
  app/src/main/java/com/juniori/puzzle/util/GalleryType.kt
  app/src/main/java/com/juniori/puzzle/util/Query.kt
  app/src/main/java/com/juniori/puzzle/util/VideoFetchingState.kt
  app/src/main/res/layout/activity_playvideo.xml
  app/src/main/res/layout/fragment_playvideo_detail.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#136 fix: 이전 영상 오디오 겹치는 문제 수정, 갤러리로 돌아갔을 때 방금 본 영상 위치로 스크롤 변경
  app/src/main/java/com/juniori/puzzle/data/video/VideoRepositoryImpl2.kt
  app/src/main/java/com/juniori/puzzle/domain/entity/VideoInfoEntity.kt
  app/src/main/java/com/juniori/puzzle/domain/repository/VideoRepository.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/ChangeVideoScopeUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/DeleteVideoUseCase.kt
  app/src/main/java/com/juniori/puzzle/domain/usecase/UpdateLikeStatusUseCase.kt
  app/src/main/java/com/juniori/puzzle/ui/addvideo/upload/UploadStep2Fragment.kt
  app/src/main/java/com/juniori/puzzle/ui/othersgallery/OthersGalleryFragment.kt
  app/src/main/java/com/juniori/puzzle/ui/playvideo/PlayVideoActivity.kt
  app/src/main/java/com/juniori/puzzle/ui/playvideo/PlayVideoDetailFragment.kt
  app/src/main/java/com/juniori/puzzle/ui/playvideo/PlayVideoDetailViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/playvideo/PlayVideoViewModel.kt
  app/src/main/java/com/juniori/puzzle/ui/playvideo/VideoSwipePagerAdapter.kt
  app/src/main/res/layout/fragment_upload_step1.xml
Labels: bug
